# This is a basic workflow to help you get started with Actions

name: Qodana

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" , "releases/*"]

  # Allows you to run this workflow manually from the Actions tab
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  qodana:
  runs-on: ubuntu-latest
  permissions:
    contents: write
    pull-requests: write
    checks: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      # Runs a single command using the runners shell
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-actions@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

